[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Adicione estas linhas abaixo:
lib_deps =
    waspinator/AccelStepper @ ^1.64
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^6.21.3
